services:
  postgres:
    image: postgres:17-alpine
    restart: always
    ports:
      - "${DATABASE_PORT}:5432"
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
