services:
  postgres:
    image: postgres:17-alpine
    restart: always
    ports:
      - "${DATABASE_PORT}:5432"
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}'",
        ]
      interval: 10s
      timeout: 3s
      retries: 3

  backend:
    depends_on:
      postgres:
        condition: service_healthy
    build:
      context: ./api-fair-impact
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${API_PORT}:3001"
    env_file:
      - .env

  frontend:
    depends_on:
      - backend
    build:
      context: ./client-fair-impact
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${CLIENT_PORT}:3000"
    env_file:
      - .env