import {
  Language,
  LanguageStatus,
} from '../../languages/entities/language.entity';

export const languageSeeds: Partial<Language>[] = [
  { code: 'aa', englishLabel: 'Afar', nativeLabel: 'Afaraf' },
  { code: 'ab', englishLabel: 'Abkhaz', nativeLabel: 'аҧсуа бызшәа' },
  { code: 'ae', englishLabel: 'Avestan', nativeLabel: 'avesta' },
  { code: 'af', englishLabel: 'Afrikaans', nativeLabel: 'Afrikaans' },
  { code: 'ak', englishLabel: 'Akan', nativeLabel: 'Akan' },
  { code: 'am', englishLabel: 'Amharic', nativeLabel: 'አማርኛ' },
  { code: 'an', englishLabel: 'Aragonese', nativeLabel: 'aragonés' },
  { code: 'ar', englishLabel: 'Arabic', nativeLabel: 'العربية' },
  { code: 'as', englishLabel: 'Assamese', nativeLabel: 'অসমীয়া' },
  { code: 'av', englishLabel: 'Avaric', nativeLabel: 'авар мацӀ' },
  { code: 'ay', englishLabel: 'Aymara', nativeLabel: 'aymar aru' },
  { code: 'az', englishLabel: 'Azerbaijani', nativeLabel: 'azərbaycan dili' },
  { code: 'ba', englishLabel: 'Bashkir', nativeLabel: 'башҡорт теле' },
  { code: 'be', englishLabel: 'Belarusian', nativeLabel: 'беларуская мова' },
  { code: 'bg', englishLabel: 'Bulgarian', nativeLabel: 'български език' },
  { code: 'bi', englishLabel: 'Bislama', nativeLabel: 'Bislama' },
  { code: 'bm', englishLabel: 'Bambara', nativeLabel: 'bamanankan' },
  { code: 'bn', englishLabel: 'Bengali', nativeLabel: 'বাংলা' },
  { code: 'bo', englishLabel: 'Tibetan', nativeLabel: 'བོད་ཡིག' },
  { code: 'br', englishLabel: 'Breton', nativeLabel: 'brezhoneg' },
  { code: 'bs', englishLabel: 'Bosnian', nativeLabel: 'bosanski jezik' },
  { code: 'ca', englishLabel: 'Catalan', nativeLabel: 'Català' },
  { code: 'ce', englishLabel: 'Chechen', nativeLabel: 'нохчийн мотт' },
  { code: 'ch', englishLabel: 'Chamorro', nativeLabel: 'Chamoru' },
  { code: 'co', englishLabel: 'Corsican', nativeLabel: 'corsu' },
  { code: 'cr', englishLabel: 'Cree', nativeLabel: 'ᓀᐦᐃᔭᐍᐏᐣ' },
  { code: 'cs', englishLabel: 'Czech', nativeLabel: 'čeština' },
  {
    code: 'cu',
    englishLabel: 'Old Church Slavonic',
    nativeLabel: 'ѩзыкъ словѣньскъ',
  },
  { code: 'cv', englishLabel: 'Chuvash', nativeLabel: 'чӑваш чӗлхи' },
  { code: 'cy', englishLabel: 'Welsh', nativeLabel: 'Cymraeg' },
  { code: 'da', englishLabel: 'Danish', nativeLabel: 'Dansk' },
  { code: 'de', englishLabel: 'German', nativeLabel: 'Deutsch' },
  { code: 'dv', englishLabel: 'Divehi', nativeLabel: 'ދިވެހި' },
  { code: 'dz', englishLabel: 'Dzongkha', nativeLabel: 'རྫོང་ཁ' },
  { code: 'ee', englishLabel: 'Ewe', nativeLabel: 'Eʋegbe' },
  { code: 'el', englishLabel: 'Greek', nativeLabel: 'Ελληνικά' },
  {
    code: 'en',
    englishLabel: 'English',
    nativeLabel: 'English',
    status: LanguageStatus.ENABLED,
  },
  { code: 'eo', englishLabel: 'Esperanto', nativeLabel: 'Esperanto' },
  { code: 'es', englishLabel: 'Spanish', nativeLabel: 'Español' },
  { code: 'et', englishLabel: 'Estonian', nativeLabel: 'eesti' },
  { code: 'eu', englishLabel: 'Basque', nativeLabel: 'euskara' },
  { code: 'fa', englishLabel: 'Persian', nativeLabel: 'فارسی' },
  { code: 'ff', englishLabel: 'Fula', nativeLabel: 'Fulfulde' },
  { code: 'fi', englishLabel: 'Finnish', nativeLabel: 'suomi' },
  { code: 'fj', englishLabel: 'Fijian', nativeLabel: 'vosa Vakaviti' },
  { code: 'fo', englishLabel: 'Faroese', nativeLabel: 'Føroyskt' },
  { code: 'fr', englishLabel: 'French', nativeLabel: 'Français' },
  { code: 'fy', englishLabel: 'Western Frisian', nativeLabel: 'Frysk' },
  { code: 'ga', englishLabel: 'Irish', nativeLabel: 'Gaeilge' },
  { code: 'gd', englishLabel: 'Scottish Gaelic', nativeLabel: 'Gàidhlig' },
  { code: 'gl', englishLabel: 'Galician', nativeLabel: 'galego' },
  { code: 'gn', englishLabel: 'Guaraní', nativeLabel: "Avañe'ẽ" },
  { code: 'gu', englishLabel: 'Gujarati', nativeLabel: 'ગુજરાતી' },
  { code: 'gv', englishLabel: 'Manx', nativeLabel: 'Gaelg' },
  { code: 'ha', englishLabel: 'Hausa', nativeLabel: 'هَوُسَ' },
  { code: 'he', englishLabel: 'Hebrew', nativeLabel: 'עברית' },
  { code: 'hi', englishLabel: 'Hindi', nativeLabel: 'हिन्दी' },
  { code: 'ho', englishLabel: 'Hiri Motu', nativeLabel: 'Hiri Motu' },
  { code: 'hr', englishLabel: 'Croatian', nativeLabel: 'Hrvatski' },
  { code: 'ht', englishLabel: 'Haitian', nativeLabel: 'Kreyòl ayisyen' },
  { code: 'hu', englishLabel: 'Hungarian', nativeLabel: 'magyar' },
  { code: 'hy', englishLabel: 'Armenian', nativeLabel: 'Հայերեն' },
  { code: 'hz', englishLabel: 'Herero', nativeLabel: 'Otjiherero' },
  { code: 'ia', englishLabel: 'Interlingua', nativeLabel: 'Interlingua' },
  { code: 'id', englishLabel: 'Indonesian', nativeLabel: 'Bahasa Indonesia' },
  { code: 'ie', englishLabel: 'Interlingue', nativeLabel: 'Interlingue' },
  { code: 'ig', englishLabel: 'Igbo', nativeLabel: 'Asụsụ Igbo' },
  { code: 'ii', englishLabel: 'Nuosu', nativeLabel: 'ꆈꌠ꒿ Nuosuhxop' },
  { code: 'ik', englishLabel: 'Inupiaq', nativeLabel: 'Iñupiaq' },
  { code: 'io', englishLabel: 'Ido', nativeLabel: 'Ido' },
  { code: 'is', englishLabel: 'Icelandic', nativeLabel: 'Íslenska' },
  { code: 'it', englishLabel: 'Italian', nativeLabel: 'Italiano' },
  { code: 'iu', englishLabel: 'Inuktitut', nativeLabel: 'ᐃᓄᒃᑎᑐᑦ' },
  { code: 'ja', englishLabel: 'Japanese', nativeLabel: '日本語' },
  { code: 'jv', englishLabel: 'Javanese', nativeLabel: 'basa Jawa' },
  { code: 'ka', englishLabel: 'Georgian', nativeLabel: 'ქართული' },
  { code: 'kg', englishLabel: 'Kongo', nativeLabel: 'Kikongo' },
  { code: 'ki', englishLabel: 'Kikuyu', nativeLabel: 'Gĩkũyũ' },
  { code: 'kj', englishLabel: 'Kwanyama', nativeLabel: 'Kuanyama' },
  { code: 'kk', englishLabel: 'Kazakh', nativeLabel: 'қазақ тілі' },
  { code: 'kl', englishLabel: 'Kalaallisut', nativeLabel: 'kalaallisut' },
  { code: 'km', englishLabel: 'Khmer', nativeLabel: 'ខេមរភាសា' },
  { code: 'kn', englishLabel: 'Kannada', nativeLabel: 'ಕನ್ನಡ' },
  { code: 'ko', englishLabel: 'Korean', nativeLabel: '한국어' },
  { code: 'kr', englishLabel: 'Kanuri', nativeLabel: 'Kanuri' },
  { code: 'ks', englishLabel: 'Kashmiri', nativeLabel: 'कश्मीरी' },
  { code: 'ku', englishLabel: 'Kurdish', nativeLabel: 'Kurdî' },
  { code: 'kv', englishLabel: 'Komi', nativeLabel: 'коми кыв' },
  { code: 'kw', englishLabel: 'Cornish', nativeLabel: 'Kernewek' },
  { code: 'ky', englishLabel: 'Kyrgyz', nativeLabel: 'Кыргызча' },
  { code: 'la', englishLabel: 'Latin', nativeLabel: 'latine' },
  { code: 'lb', englishLabel: 'Luxembourgish', nativeLabel: 'Lëtzebuergesch' },
  { code: 'lg', englishLabel: 'Ganda', nativeLabel: 'Luganda' },
  { code: 'li', englishLabel: 'Limburgish', nativeLabel: 'Limburgs' },
  { code: 'ln', englishLabel: 'Lingala', nativeLabel: 'Lingála' },
  { code: 'lo', englishLabel: 'Lao', nativeLabel: 'ພາສາລາວ' },
  { code: 'lt', englishLabel: 'Lithuanian', nativeLabel: 'lietuvių kalba' },
  { code: 'lu', englishLabel: 'Luba-Katanga', nativeLabel: 'Kiluba' },
  { code: 'lv', englishLabel: 'Latvian', nativeLabel: 'latviešu valoda' },
  { code: 'mg', englishLabel: 'Malagasy', nativeLabel: 'fiteny malagasy' },
  { code: 'mh', englishLabel: 'Marshallese', nativeLabel: 'Kajin M̧ajeļ' },
  { code: 'mi', englishLabel: 'Māori', nativeLabel: 'te reo Māori' },
  { code: 'mk', englishLabel: 'Macedonian', nativeLabel: 'македонски јазик' },
  { code: 'ml', englishLabel: 'Malayalam', nativeLabel: 'മലയാളം' },
  { code: 'mn', englishLabel: 'Mongolian', nativeLabel: 'Монгол хэл' },
  { code: 'mr', englishLabel: 'Marathi', nativeLabel: 'मराठी' },
  { code: 'ms', englishLabel: 'Malay', nativeLabel: 'Bahasa Melayu' },
  { code: 'mt', englishLabel: 'Maltese', nativeLabel: 'Malti' },
  { code: 'my', englishLabel: 'Burmese', nativeLabel: 'ဗမာစာ' },
  { code: 'na', englishLabel: 'Nauru', nativeLabel: 'Dorerin Naoero' },
  { code: 'nb', englishLabel: 'Norwegian Bokmål', nativeLabel: 'Norsk bokmål' },
  { code: 'nd', englishLabel: 'Northern Ndebele', nativeLabel: 'isiNdebele' },
  { code: 'ne', englishLabel: 'Nepali', nativeLabel: 'नेपाली' },
  { code: 'ng', englishLabel: 'Ndonga', nativeLabel: 'Owambo' },
  { code: 'nl', englishLabel: 'Dutch', nativeLabel: 'Nederlands' },
  {
    code: 'nn',
    englishLabel: 'Norwegian Nynorsk',
    nativeLabel: 'Norsk nynorsk',
  },
  { code: 'no', englishLabel: 'Norwegian', nativeLabel: 'Norsk' },
  { code: 'nr', englishLabel: 'Southern Ndebele', nativeLabel: 'isiNdebele' },
  { code: 'nv', englishLabel: 'Navajo', nativeLabel: 'Diné bizaad' },
  { code: 'ny', englishLabel: 'Chichewa', nativeLabel: 'chiCheŵa' },
  { code: 'oc', englishLabel: 'Occitan', nativeLabel: 'occitan' },
  { code: 'oj', englishLabel: 'Ojibwe', nativeLabel: 'ᐊᓂᔑᓈᐯᒧᐎᓐ' },
  { code: 'om', englishLabel: 'Oromo', nativeLabel: 'Afaan Oromoo' },
  { code: 'or', englishLabel: 'Oriya', nativeLabel: 'ଓଡ଼ିଆ' },
  { code: 'os', englishLabel: 'Ossetian', nativeLabel: 'ирон æвзаг' },
  { code: 'pa', englishLabel: 'Panjabi', nativeLabel: 'ਪੰਜਾਬੀ' },
  { code: 'pi', englishLabel: 'Pāli', nativeLabel: 'पाऴि' },
  { code: 'pl', englishLabel: 'Polish', nativeLabel: 'Polski' },
  { code: 'ps', englishLabel: 'Pashto', nativeLabel: 'پښتو' },
  { code: 'pt', englishLabel: 'Portuguese', nativeLabel: 'Português' },
  { code: 'qu', englishLabel: 'Quechua', nativeLabel: 'Runa Simi' },
  { code: 'rm', englishLabel: 'Romansh', nativeLabel: 'rumantsch grischun' },
  { code: 'rn', englishLabel: 'Kirundi', nativeLabel: 'Ikirundi' },
  { code: 'ro', englishLabel: 'Romanian', nativeLabel: 'Română' },
  { code: 'ru', englishLabel: 'Russian', nativeLabel: 'Русский' },
  { code: 'rw', englishLabel: 'Kinyarwanda', nativeLabel: 'Ikinyarwanda' },
  { code: 'sa', englishLabel: 'Sanskrit', nativeLabel: 'संस्कृतम्' },
  { code: 'sc', englishLabel: 'Sardinian', nativeLabel: 'sardu' },
  { code: 'sd', englishLabel: 'Sindhi', nativeLabel: 'सिन्धी' },
  { code: 'se', englishLabel: 'Northern Sami', nativeLabel: 'Davvisámegiella' },
  { code: 'sg', englishLabel: 'Sango', nativeLabel: 'yângâ tî sängö' },
  { code: 'si', englishLabel: 'Sinhala', nativeLabel: 'සිංහල' },
  { code: 'sk', englishLabel: 'Slovak', nativeLabel: 'slovenčina' },
  { code: 'sl', englishLabel: 'Slovenian', nativeLabel: 'slovenščina' },
  { code: 'sm', englishLabel: 'Samoan', nativeLabel: "gagana fa'a Samoa" },
  { code: 'sn', englishLabel: 'Shona', nativeLabel: 'chiShona' },
  { code: 'so', englishLabel: 'Somali', nativeLabel: 'Soomaaliga' },
  { code: 'sq', englishLabel: 'Albanian', nativeLabel: 'Shqip' },
  { code: 'sr', englishLabel: 'Serbian', nativeLabel: 'српски језик' },
  { code: 'ss', englishLabel: 'Swati', nativeLabel: 'SiSwati' },
  { code: 'st', englishLabel: 'Southern Sotho', nativeLabel: 'Sesotho' },
  { code: 'su', englishLabel: 'Sundanese', nativeLabel: 'Basa Sunda' },
  { code: 'sv', englishLabel: 'Swedish', nativeLabel: 'Svenska' },
  { code: 'sw', englishLabel: 'Swahili', nativeLabel: 'Kiswahili' },
  { code: 'ta', englishLabel: 'Tamil', nativeLabel: 'தமிழ்' },
  { code: 'te', englishLabel: 'Telugu', nativeLabel: 'తెలుగు' },
  { code: 'tg', englishLabel: 'Tajik', nativeLabel: 'тоҷикӣ' },
  { code: 'th', englishLabel: 'Thai', nativeLabel: 'ไทย' },
  { code: 'ti', englishLabel: 'Tigrinya', nativeLabel: 'ትግርኛ' },
  { code: 'tk', englishLabel: 'Turkmen', nativeLabel: 'Türkmençe' },
  { code: 'tl', englishLabel: 'Tagalog', nativeLabel: 'Wikang Tagalog' },
  { code: 'tn', englishLabel: 'Tswana', nativeLabel: 'Setswana' },
  { code: 'to', englishLabel: 'Tonga', nativeLabel: 'faka Tonga' },
  { code: 'tr', englishLabel: 'Turkish', nativeLabel: 'Türkçe' },
  { code: 'ts', englishLabel: 'Tsonga', nativeLabel: 'Xitsonga' },
  { code: 'tt', englishLabel: 'Tatar', nativeLabel: 'татар теле' },
  { code: 'tw', englishLabel: 'Twi', nativeLabel: 'Twi' },
  { code: 'ty', englishLabel: 'Tahitian', nativeLabel: 'Reo Tahiti' },
  { code: 'ug', englishLabel: 'Uyghur', nativeLabel: 'ئۇيغۇرچە‎' },
  { code: 'uk', englishLabel: 'Ukrainian', nativeLabel: 'Українська' },
  { code: 'ur', englishLabel: 'Urdu', nativeLabel: 'اردو' },
  { code: 'uz', englishLabel: 'Uzbek', nativeLabel: 'Ўзбек' },
  { code: 've', englishLabel: 'Venda', nativeLabel: 'Tshivenḓa' },
  { code: 'vi', englishLabel: 'VietenglishLabelse', nativeLabel: 'Tiếng Việt' },
  { code: 'vo', englishLabel: 'Volapük', nativeLabel: 'Volapük' },
  { code: 'wa', englishLabel: 'Walloon', nativeLabel: 'walon' },
  { code: 'wo', englishLabel: 'Wolof', nativeLabel: 'Wollof' },
  { code: 'xh', englishLabel: 'Xhosa', nativeLabel: 'isiXhosa' },
  { code: 'yi', englishLabel: 'Yiddish', nativeLabel: 'ייִדיש' },
  { code: 'yo', englishLabel: 'Yoruba', nativeLabel: 'Yorùbá' },
  { code: 'za', englishLabel: 'Zhuang', nativeLabel: 'Saɯ cueŋƅ' },
  { code: 'zh', englishLabel: 'Chinese', nativeLabel: '中文' },
  { code: 'zu', englishLabel: 'Zulu', nativeLabel: 'isiZulu' },
];
